# Generated by Django 4.2.3 on 2024-09-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='id_user',
            field=models.IntegerField(default=0),
        ),
    ]
