# Generated by Django 4.2.3 on 2024-09-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC', '0002_paciente_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='historiaclinica',
        ),
        migrations.AddField(
            model_name='paciente',
            name='AntecedentesMedicos',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ApoyoSocial',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='CondicionesMedicasAct',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='FrecuenciadeSecciones',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='His_problemasPsicologicos',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='His_tratamientoAnteriones',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='HistoriadeVida',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='IntervencionesyEstrategias',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='RelacionesInterpersonales',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='SintomasActuales',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='TipoDocumento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('PA', 'Pasaporte')], default='CC', max_length=2),
        ),
        migrations.AddField(
            model_name='paciente',
            name='antecedentesdeEnfermedadesMentales',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellidos',
            field=models.CharField(default='Apellido Temporal', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ciudad_residencia',
            field=models.CharField(choices=[('Bogotá', 'Bogotá'), ('Medellín', 'Medellín'), ('Cali', 'Cali'), ('Barranquilla', 'Barranquilla'), ('Cartagena', 'Cartagena'), ('Cúcuta', 'Cúcuta'), ('Bucaramanga', 'Bucaramanga'), ('Pereira', 'Pereira'), ('Santa Marta', 'Santa Marta'), ('Ibagué', 'Ibagué')], default='Bogotá', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='composicionFamiliar',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion_domicilio',
            field=models.CharField(default='Dirección Temporal', max_length=200),
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfoqueterapeutico',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='eps',
            field=models.CharField(default='EPS Temporal', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(default='Estado Civil Temporal', max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='evalucionDiagnosticaPreliminar',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fechaNacimiento',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], default='Masculino', max_length=10),
        ),
        migrations.AddField(
            model_name='paciente',
            name='motivoConsulta',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombreAcompanante',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='paciente',
            name='objetivosdelaTerapia',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(default='Ocupación Temporal', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='parentesco',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tel_contacto',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tel_contacto_acompanante',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(default='Nombre Temporal', max_length=100),
        ),
    ]
