# Generated by Django 4.2.3 on 2024-10-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC', '0003_remove_paciente_historiaclinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Examenes_clinicos',
            field=models.FileField(blank=True, null=True, upload_to='archivos_clinicos/'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fechaCreacion',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='num_historiaclinica',
            field=models.IntegerField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cc',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ciudad_residencia',
            field=models.CharField(choices=[('Bogotá', 'Bogotá'), ('Medellín', 'Medellín'), ('Cali', 'Cali'), ('Barranquilla', 'Barranquilla'), ('Cartagena', 'Cartagena'), ('Cúcuta', 'Cúcuta'), ('Bucaramanga', 'Bucaramanga'), ('Pereira', 'Pereira'), ('Santa Marta', 'Santa Marta'), ('Ibagué', 'Ibagué')], max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion_domicilio',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='eps',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tel_contacto',
            field=models.CharField(max_length=20),
        ),
    ]
