# Generated by Django 4.2.3 on 2024-10-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC', '0004_paciente_examenes_clinicos_paciente_fechacreacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
