# Generated by Django 4.2.3 on 2024-10-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC', '0005_alter_paciente_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
