# Generated by Django 4.2.3 on 2024-10-15 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HC', '0006_alter_paciente_fechacreacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evoluciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('evolucion', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HC.paciente')),
            ],
        ),
    ]
