# Generated by Django 4.2.3 on 2024-10-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HC', '0007_evoluciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evoluciones',
            old_name='paciente',
            new_name='cc_paciente',
        ),
    ]
