# Generated by Django 4.2.3 on 2024-10-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HC', '0008_rename_paciente_evoluciones_cc_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id_user', models.IntegerField(default=0)),
                ('cc_profesional', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('NombreApellidos', models.CharField(max_length=254)),
                ('Foto', models.ImageField(blank=True, null=True, upload_to='fotos_profesionales/')),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10)),
                ('direccion', models.CharField(max_length=200)),
                ('Profesion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('tel_contacto', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=100)),
                ('horarioAtencion', models.CharField(max_length=100)),
                ('codigoPrestador', models.IntegerField(default=0)),
            ],
        ),
    ]
